/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import GUISS.LogIn;
import GUISS.MenuPrincipalUserBasico;
import GUISS.MenuPrincipalUserPremium;
import Model.Clases.Cliente;
import Model.Clases.Steam;
import Model.Clases.UserBasico;
import Model.Clases.UsuarioPremium;
import Model.Clases.Validar;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author paola
 */
public class vistaAjustes extends javax.swing.JPanel {

    /**
     * Creates new form vistaAjustes
     */
    
    private Cliente cliente;
    private Steam steam;
    private Boolean eliminado;
    private ObjectMapper mapper;
    private File file;
    private LogIn lw;
    private MenuPrincipalUserBasico mb;
    private MenuPrincipalUserPremium mp;
    
    public vistaAjustes(Cliente cliente,Steam steam,LogIn lw, MenuPrincipalUserPremium mp, MenuPrincipalUserBasico mb,ObjectMapper mapper, File file) {
        this.cliente=cliente;
        this.steam=steam;
        this.lw=lw;
        this.mp=mp;
        this.mb=mb;
        this.mapper=mapper;
        this.file=file;
        initComponents();
        Boolean eliminado=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoModificar = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoApellido = new javax.swing.JLabel();
        textoContrasenia = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        campoApellido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        campoEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        campoContrasenia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        fondoAceptarApellido = new javax.swing.JPanel();
        botonAceptarApellido = new javax.swing.JLabel();
        fondoAceptarEmail = new javax.swing.JPanel();
        textoAceptarEmail = new javax.swing.JLabel();
        fondoAceptarContrasenia = new javax.swing.JPanel();
        textoAceptarContrasenia = new javax.swing.JLabel();
        fondoAceptarNombre = new javax.swing.JPanel();
        textoAceptarNombre = new javax.swing.JLabel();
        fondoCambiarCuenta = new javax.swing.JPanel();
        textoCambiarTipo = new javax.swing.JLabel();
        fondoDarseDeBaja = new javax.swing.JPanel();
        textoDarseDeBaja = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        textoModificar.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        textoModificar.setForeground(new java.awt.Color(255, 255, 255));
        textoModificar.setText("Modificar:");

        textoNombre.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("Nombre:");

        textoApellido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(255, 255, 255));
        textoApellido.setText("Apellido:");

        textoContrasenia.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        textoContrasenia.setText("Contraseña:");

        textoEmail.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoEmail.setForeground(new java.awt.Color(255, 255, 255));
        textoEmail.setText("E-Mail:");

        campoNombre.setBackground(new java.awt.Color(51, 51, 51));
        campoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setText("Ingrese su nuevo nombre");
        campoNombre.setBorder(null);

        campoApellido.setBackground(new java.awt.Color(51, 51, 51));
        campoApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoApellido.setForeground(new java.awt.Color(255, 255, 255));
        campoApellido.setText("Ingrese su nuevo apellido");
        campoApellido.setBorder(null);

        campoEmail.setBackground(new java.awt.Color(51, 51, 51));
        campoEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(255, 255, 255));
        campoEmail.setText("Ingrese su nuevo e-mail");
        campoEmail.setBorder(null);

        campoContrasenia.setBackground(new java.awt.Color(51, 51, 51));
        campoContrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        campoContrasenia.setText("Ingrese su nueva contraseña");
        campoContrasenia.setBorder(null);

        fondoAceptarApellido.setBackground(new java.awt.Color(153, 0, 255));

        botonAceptarApellido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonAceptarApellido.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptarApellido.setText("   Aceptar");
        botonAceptarApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarApellidoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAceptarApellidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAceptarApellidoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoAceptarApellidoLayout = new javax.swing.GroupLayout(fondoAceptarApellido);
        fondoAceptarApellido.setLayout(fondoAceptarApellidoLayout);
        fondoAceptarApellidoLayout.setHorizontalGroup(
            fondoAceptarApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoAceptarApellidoLayout.setVerticalGroup(
            fondoAceptarApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        fondoAceptarEmail.setBackground(new java.awt.Color(153, 0, 255));

        textoAceptarEmail.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        textoAceptarEmail.setForeground(new java.awt.Color(255, 255, 255));
        textoAceptarEmail.setText("   Aceptar");
        textoAceptarEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAceptarEmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoAceptarEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoAceptarEmailMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoAceptarEmailLayout = new javax.swing.GroupLayout(fondoAceptarEmail);
        fondoAceptarEmail.setLayout(fondoAceptarEmailLayout);
        fondoAceptarEmailLayout.setHorizontalGroup(
            fondoAceptarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoAceptarEmailLayout.setVerticalGroup(
            fondoAceptarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        fondoAceptarContrasenia.setBackground(new java.awt.Color(153, 0, 255));

        textoAceptarContrasenia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        textoAceptarContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        textoAceptarContrasenia.setText("   Aceptar");
        textoAceptarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAceptarContraseniaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoAceptarContraseniaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoAceptarContraseniaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoAceptarContraseniaLayout = new javax.swing.GroupLayout(fondoAceptarContrasenia);
        fondoAceptarContrasenia.setLayout(fondoAceptarContraseniaLayout);
        fondoAceptarContraseniaLayout.setHorizontalGroup(
            fondoAceptarContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoAceptarContraseniaLayout.setVerticalGroup(
            fondoAceptarContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        fondoAceptarNombre.setBackground(new java.awt.Color(153, 0, 255));

        textoAceptarNombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        textoAceptarNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoAceptarNombre.setText("   Aceptar");
        textoAceptarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAceptarNombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoAceptarNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoAceptarNombreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoAceptarNombreLayout = new javax.swing.GroupLayout(fondoAceptarNombre);
        fondoAceptarNombre.setLayout(fondoAceptarNombreLayout);
        fondoAceptarNombreLayout.setHorizontalGroup(
            fondoAceptarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoAceptarNombreLayout.setVerticalGroup(
            fondoAceptarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAceptarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        fondoCambiarCuenta.setBackground(new java.awt.Color(153, 0, 255));

        textoCambiarTipo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoCambiarTipo.setForeground(new java.awt.Color(255, 255, 255));
        textoCambiarTipo.setText(" Cambiar tipo de cuenta");
        textoCambiarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoCambiarTipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoCambiarTipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoCambiarTipoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoCambiarCuentaLayout = new javax.swing.GroupLayout(fondoCambiarCuenta);
        fondoCambiarCuenta.setLayout(fondoCambiarCuentaLayout);
        fondoCambiarCuentaLayout.setHorizontalGroup(
            fondoCambiarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCambiarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        fondoCambiarCuentaLayout.setVerticalGroup(
            fondoCambiarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCambiarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoDarseDeBaja.setBackground(new java.awt.Color(153, 0, 255));

        textoDarseDeBaja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoDarseDeBaja.setForeground(new java.awt.Color(255, 255, 255));
        textoDarseDeBaja.setText("        Darse de baja");
        textoDarseDeBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoDarseDeBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoDarseDeBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoDarseDeBajaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoDarseDeBajaLayout = new javax.swing.GroupLayout(fondoDarseDeBaja);
        fondoDarseDeBaja.setLayout(fondoDarseDeBajaLayout);
        fondoDarseDeBajaLayout.setHorizontalGroup(
            fondoDarseDeBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoDarseDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        fondoDarseDeBajaLayout.setVerticalGroup(
            fondoDarseDeBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoDarseDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textoContrasenia)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textoApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(campoApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(textoEmail)
                                                .addGap(28, 28, 28)
                                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addComponent(campoContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jSeparator4)))))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondoAceptarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoAceptarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoAceptarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoAceptarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(fondoCambiarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(fondoDarseDeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fondoAceptarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fondoAceptarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoAceptarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoAceptarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fondoDarseDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoCambiarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Boolean eliminado(){
        return eliminado;
    }
    private void textoAceptarNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarNombreMouseEntered
        // TODO add your handling code here:
        fondoAceptarNombre.setBackground(new Color(153,0,236));
        
    }//GEN-LAST:event_textoAceptarNombreMouseEntered

    private void textoAceptarNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarNombreMouseExited
        // TODO add your handling code here:
        fondoAceptarNombre.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoAceptarNombreMouseExited

    private void botonAceptarApellidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarApellidoMouseEntered
        // TODO add your handling code here:
        fondoAceptarApellido.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAceptarApellidoMouseEntered

    private void botonAceptarApellidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarApellidoMouseExited
        // TODO add your handling code here:
        fondoAceptarApellido.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonAceptarApellidoMouseExited

    private void textoAceptarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarNombreMouseClicked
        // TODO add your handling code here:
        if(!campoNombre.getText().equals("Ingrese su nuevo nombre")){
        this.cliente.setNombre(campoNombre.getText());
            JOptionPane.showMessageDialog(this, "Nombre cambiado correctamente");
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un nombe");
        }
    }//GEN-LAST:event_textoAceptarNombreMouseClicked

    private void textoAceptarEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarEmailMouseClicked
        // TODO add your handling code here:
       if(!campoEmail.getText().equals("Ingrese su nuevo e-mail"))
       {
        ArrayList<Boolean> validaciones=Validar.mail(campoEmail.getText(), this.steam.getUsuariosPremium(),this.steam.getUsersBasicos());
        if(validaciones.get(0)==true){
            this.cliente.setMail(campoEmail.getText());
            JOptionPane.showMessageDialog(this, "Mail cambiado exitosamente");
        }else if(validaciones.get(1)==false){
            JOptionPane.showMessageDialog(this, "El mail no continene @ o .com");
        }else if(validaciones.get(2)==false){
            JOptionPane.showMessageDialog(this, "El mail ya se encuentra registrado en el sistema");
        }
       }
    }//GEN-LAST:event_textoAceptarEmailMouseClicked

    private void textoAceptarEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarEmailMouseEntered
        // TODO add your handling code here:
        fondoAceptarEmail.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoAceptarEmailMouseEntered

    private void textoAceptarEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarEmailMouseExited
        // TODO add your handling code here:
        fondoAceptarEmail.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoAceptarEmailMouseExited

    private void textoAceptarContraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarContraseniaMouseClicked
        // TODO add your handling code here:
        if(!campoContrasenia.getText().equals("Ingrese su nueva contraseña")){
            ArrayList<Boolean> validacion = Validar.contrasena(campoContrasenia.getText());
            if(validacion.get(0)==true){
                this.cliente.setContrasena(campoContrasenia.getText());
                JOptionPane.showMessageDialog(this, "contraseña cambiada correctamente");
            }else if(validacion.get(1)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos una mayuscula");
            }else if(validacion.get(2)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos un numero");
            }else if(validacion.get(3)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos ocho caracteres");
            }
        }
        
    }//GEN-LAST:event_textoAceptarContraseniaMouseClicked

    private void textoAceptarContraseniaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarContraseniaMouseEntered
        // TODO add your handling code here:
        fondoAceptarContrasenia.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoAceptarContraseniaMouseEntered

    private void textoAceptarContraseniaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAceptarContraseniaMouseExited
        // TODO add your handling code here:
        fondoAceptarContrasenia.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoAceptarContraseniaMouseExited

    private void textoCambiarTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCambiarTipoMouseClicked
        // TODO add your handling code here:
        int valor=JOptionPane.showConfirmDialog(this, "Realmente desea cambiar de cuenta?", "Warning cambio de cuenta", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){
            if(this.cliente instanceof UserBasico){
                this.steam.modificarAPremium((UserBasico) this.cliente);
            }else{
                this.steam.modificarABasico((UsuarioPremium) this.cliente);
            }
            try {
                this.mapper.writerWithDefaultPrettyPrinter().writeValue(this.file,this.steam);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            lw.setVisible(true);
            if(mb != null){
                mb.dispose();
            } else if (mp != null) {
                mp.dispose();
            }
            JOptionPane.showMessageDialog(this, "Usted a cambiado de tipo de cuenta");
        }
    }//GEN-LAST:event_textoCambiarTipoMouseClicked

    private void textoCambiarTipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCambiarTipoMouseEntered
        // TODO add your handling code here:
        fondoCambiarCuenta.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoCambiarTipoMouseEntered

    private void textoCambiarTipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCambiarTipoMouseExited
        // TODO add your handling code here:
        fondoCambiarCuenta.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoCambiarTipoMouseExited

    private void textoDarseDeBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDarseDeBajaMouseClicked
        // TODO add your handling code here:
        int valor=JOptionPane.showConfirmDialog(this, "Realmente desea darse de baja?", "Warning baja", JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){
            this.steam.darDeBajaUsuario(this.cliente.getDni());
            try {
                this.mapper.writerWithDefaultPrettyPrinter().writeValue(this.file,this.steam);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            lw.setVisible(true);
            if(mb != null){
                mb.dispose();
            } else if (mp != null) {
                mp.dispose();
            }
            JOptionPane.showMessageDialog(this, "Usted se a dado de baja");
        }
    }//GEN-LAST:event_textoDarseDeBajaMouseClicked

    private void textoDarseDeBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDarseDeBajaMouseEntered
        // TODO add your handling code here:
        fondoDarseDeBaja.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoDarseDeBajaMouseEntered

    private void textoDarseDeBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDarseDeBajaMouseExited
        // TODO add your handling code here:
        fondoDarseDeBaja.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoDarseDeBajaMouseExited

    private void botonAceptarApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarApellidoMouseClicked
        // TODO add your handling code here:
        if(!campoApellido.getText().equals("Ingrese su nuevo apellido")){
           this.cliente.setApellido(campoApellido.getText());
            JOptionPane.showMessageDialog(this,"Apellido cambiado correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese un apellido");
        }
    }//GEN-LAST:event_botonAceptarApellidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAceptarApellido;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoContrasenia;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel fondoAceptarApellido;
    private javax.swing.JPanel fondoAceptarContrasenia;
    private javax.swing.JPanel fondoAceptarEmail;
    private javax.swing.JPanel fondoAceptarNombre;
    private javax.swing.JPanel fondoCambiarCuenta;
    private javax.swing.JPanel fondoDarseDeBaja;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel textoAceptarContrasenia;
    private javax.swing.JLabel textoAceptarEmail;
    private javax.swing.JLabel textoAceptarNombre;
    private javax.swing.JLabel textoApellido;
    private javax.swing.JLabel textoCambiarTipo;
    private javax.swing.JLabel textoContrasenia;
    private javax.swing.JLabel textoDarseDeBaja;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoModificar;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
