/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Cliente;
import Model.Clases.MovimientoEconomico;
import Model.Clases.MovimientoEconomico.tipoDeMovimiento;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paola
 */
public class vistaCargarSaldo extends javax.swing.JPanel {

    private Cliente cliente;
    /**
     * Creates new form vistaCargarSaldo
     */
    public vistaCargarSaldo(Cliente cliente) {
        this.cliente=cliente;
        initComponents();
        llenarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        extracto = new javax.swing.JTable();
        textoExtracto = new javax.swing.JLabel();
        fieldIngresarSaldo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelFondoCargar = new javax.swing.JPanel();
        botonCargarSaldo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        extracto.setBackground(new java.awt.Color(51, 51, 51));
        extracto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        extracto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        extracto.setForeground(new java.awt.Color(255, 255, 255));
        extracto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Movimineto", "Valor", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(extracto);

        textoExtracto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoExtracto.setForeground(new java.awt.Color(255, 255, 255));
        textoExtracto.setText("Extracto de cuenta");

        fieldIngresarSaldo.setBackground(new java.awt.Color(51, 51, 51));
        fieldIngresarSaldo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldIngresarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        fieldIngresarSaldo.setBorder(null);

        panelFondoCargar.setBackground(new java.awt.Color(153, 0, 255));

        botonCargarSaldo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonCargarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarSaldo.setText("   Cargar");
        botonCargarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelFondoCargarLayout = new javax.swing.GroupLayout(panelFondoCargar);
        panelFondoCargar.setLayout(panelFondoCargarLayout);
        panelFondoCargarLayout.setHorizontalGroup(
            panelFondoCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCargarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        panelFondoCargarLayout.setVerticalGroup(
            panelFondoCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCargarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldIngresarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(panelFondoCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoExtracto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textoExtracto, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(fieldIngresarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFondoCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void llenarJTable(){
        DefaultTableModel datos=(DefaultTableModel)extracto.getModel();
        datos.setNumRows(0);
        for(MovimientoEconomico mov: this.cliente.getExtractoDeCuenta()){
                Object [] fila = {mov.getTipo(),mov.getMagnitud(),mov.getFecha()};
                datos.addRow(fila);
        }
    }
    
    private void botonCargarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseClicked
        // TODO add your handling code here:
        try{
            Double ingreso=Double.parseDouble(fieldIngresarSaldo.getText());
            this.cliente.CargarSaldo(ingreso);
            this.cliente.getExtractoDeCuenta().add(new MovimientoEconomico(tipoDeMovimiento.INGRESO,ingreso));
            llenarJTable();
        }catch(NumberFormatException e){
            JOptionPane.showConfirmDialog(this,"Ingrese solo numeros");
        }
        
    }//GEN-LAST:event_botonCargarSaldoMouseClicked

    private void botonCargarSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseEntered
        // TODO add your handling code here:
        panelFondoCargar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonCargarSaldoMouseEntered

    private void botonCargarSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseExited
        // TODO add your handling code here:
        panelFondoCargar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonCargarSaldoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCargarSaldo;
    private javax.swing.JTable extracto;
    private javax.swing.JTextField fieldIngresarSaldo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelFondoCargar;
    private javax.swing.JLabel textoExtracto;
    // End of variables declaration//GEN-END:variables
}
