/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Juego;
import Model.Clases.Steam;
import Model.Clases.Validar;
import Model.Enums.EJuegos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author paola
 */
public class vistaCrearJuego extends javax.swing.JPanel {

    private Steam steam;
    private Juego juego;
    /**
     * Creates new form vistaCrearAdmin
     */
    public vistaCrearJuego(Steam steam) {
        this.steam=steam;
        this.juego=new Juego();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoNombre = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        textoRegistroUsuario = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoPrecio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        textoCategoria = new javax.swing.JLabel();
        textoPrecio = new javax.swing.JLabel();
        fondoBotonCrearJuego = new javax.swing.JPanel();
        botonCrear = new javax.swing.JLabel();
        barraDeCategorias = new javax.swing.JPanel();
        fondoBotonAccion = new javax.swing.JPanel();
        botonAccion = new javax.swing.JLabel();
        fondoBotonAventura = new javax.swing.JPanel();
        botonAventura = new javax.swing.JLabel();
        fondoBotonDeRol = new javax.swing.JPanel();
        botonDeRol = new javax.swing.JLabel();
        fondoBotonDeporte = new javax.swing.JPanel();
        botonDeporte = new javax.swing.JLabel();
        fondoBotonSimulacion = new javax.swing.JPanel();
        botonSimulacion = new javax.swing.JLabel();
        fondoBotonEstrategia = new javax.swing.JPanel();
        botonEstrategia = new javax.swing.JLabel();
        textoLinkVideo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        campoLinkVideo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(654, 425));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(654, 555));

        textoNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("                  Nombre:");

        barraSuperior.setBackground(new java.awt.Color(153, 0, 255));

        textoRegistroUsuario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoRegistroUsuario.setText("Crear nuevo juego");

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(textoRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoRegistroUsuario)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        campoNombre.setBackground(new java.awt.Color(51, 51, 51));
        campoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setBorder(null);

        campoPrecio.setBackground(new java.awt.Color(51, 51, 51));
        campoPrecio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        campoPrecio.setBorder(null);

        textoCategoria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        textoCategoria.setText("Categoria:");

        textoPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        textoPrecio.setText(" Precio:");

        fondoBotonCrearJuego.setBackground(new java.awt.Color(153, 0, 255));

        botonCrear.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(255, 255, 255));
        botonCrear.setText("          Crear");
        botonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCrearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonCrearJuegoLayout = new javax.swing.GroupLayout(fondoBotonCrearJuego);
        fondoBotonCrearJuego.setLayout(fondoBotonCrearJuegoLayout);
        fondoBotonCrearJuegoLayout.setHorizontalGroup(
            fondoBotonCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
            .addGroup(fondoBotonCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoBotonCrearJuegoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoBotonCrearJuegoLayout.setVerticalGroup(
            fondoBotonCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(fondoBotonCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoBotonCrearJuegoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        barraDeCategorias.setBackground(new java.awt.Color(153, 0, 255));

        fondoBotonAccion.setBackground(new java.awt.Color(153, 0, 255));

        botonAccion.setBackground(new java.awt.Color(153, 0, 255));
        botonAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonAccion.setForeground(new java.awt.Color(255, 255, 255));
        botonAccion.setText("     Accion");
        botonAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonAccionLayout = new javax.swing.GroupLayout(fondoBotonAccion);
        fondoBotonAccion.setLayout(fondoBotonAccionLayout);
        fondoBotonAccionLayout.setHorizontalGroup(
            fondoBotonAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        fondoBotonAccionLayout.setVerticalGroup(
            fondoBotonAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        fondoBotonAventura.setBackground(new java.awt.Color(153, 0, 255));

        botonAventura.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonAventura.setForeground(new java.awt.Color(255, 255, 255));
        botonAventura.setText("  Aventura");
        botonAventura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAventuraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAventuraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAventuraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonAventuraLayout = new javax.swing.GroupLayout(fondoBotonAventura);
        fondoBotonAventura.setLayout(fondoBotonAventuraLayout);
        fondoBotonAventuraLayout.setHorizontalGroup(
            fondoBotonAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAventura, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoBotonAventuraLayout.setVerticalGroup(
            fondoBotonAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAventura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoBotonDeRol.setBackground(new java.awt.Color(153, 0, 255));

        botonDeRol.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonDeRol.setForeground(new java.awt.Color(255, 255, 255));
        botonDeRol.setText("    De Rol");
        botonDeRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDeRolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDeRolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDeRolMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonDeRolLayout = new javax.swing.GroupLayout(fondoBotonDeRol);
        fondoBotonDeRol.setLayout(fondoBotonDeRolLayout);
        fondoBotonDeRolLayout.setHorizontalGroup(
            fondoBotonDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonDeRol, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        fondoBotonDeRolLayout.setVerticalGroup(
            fondoBotonDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonDeRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoBotonDeporte.setBackground(new java.awt.Color(153, 0, 255));

        botonDeporte.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonDeporte.setForeground(new java.awt.Color(255, 255, 255));
        botonDeporte.setText("   Deporte");
        botonDeporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDeporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDeporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDeporteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonDeporteLayout = new javax.swing.GroupLayout(fondoBotonDeporte);
        fondoBotonDeporte.setLayout(fondoBotonDeporteLayout);
        fondoBotonDeporteLayout.setHorizontalGroup(
            fondoBotonDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        fondoBotonDeporteLayout.setVerticalGroup(
            fondoBotonDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoBotonSimulacion.setBackground(new java.awt.Color(153, 0, 255));

        botonSimulacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        botonSimulacion.setText("Simulacion");
        botonSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSimulacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSimulacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSimulacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonSimulacionLayout = new javax.swing.GroupLayout(fondoBotonSimulacion);
        fondoBotonSimulacion.setLayout(fondoBotonSimulacionLayout);
        fondoBotonSimulacionLayout.setHorizontalGroup(
            fondoBotonSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        fondoBotonSimulacionLayout.setVerticalGroup(
            fondoBotonSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoBotonEstrategia.setBackground(new java.awt.Color(153, 0, 255));

        botonEstrategia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonEstrategia.setForeground(new java.awt.Color(255, 255, 255));
        botonEstrategia.setText(" Estrategia");
        botonEstrategia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEstrategiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEstrategiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEstrategiaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonEstrategiaLayout = new javax.swing.GroupLayout(fondoBotonEstrategia);
        fondoBotonEstrategia.setLayout(fondoBotonEstrategiaLayout);
        fondoBotonEstrategiaLayout.setHorizontalGroup(
            fondoBotonEstrategiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBotonEstrategiaLayout.createSequentialGroup()
                .addComponent(botonEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        fondoBotonEstrategiaLayout.setVerticalGroup(
            fondoBotonEstrategiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEstrategia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraDeCategoriasLayout = new javax.swing.GroupLayout(barraDeCategorias);
        barraDeCategorias.setLayout(barraDeCategoriasLayout);
        barraDeCategoriasLayout.setHorizontalGroup(
            barraDeCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeCategoriasLayout.createSequentialGroup()
                .addComponent(fondoBotonAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonAventura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonDeRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraDeCategoriasLayout.setVerticalGroup(
            barraDeCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeCategoriasLayout.createSequentialGroup()
                .addGroup(barraDeCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fondoBotonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoBotonSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoBotonAventura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoBotonDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoBotonDeRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondoBotonEstrategia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        textoLinkVideo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoLinkVideo.setForeground(new java.awt.Color(255, 255, 255));
        textoLinkVideo.setText("Link video:");

        campoLinkVideo.setBackground(new java.awt.Color(51, 51, 51));
        campoLinkVideo.setForeground(new java.awt.Color(255, 255, 255));
        campoLinkVideo.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barraDeCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(textoPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fondoBotonCrearJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoLinkVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2)
                                .addComponent(campoLinkVideo)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textoLinkVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(campoLinkVideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(barraDeCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPrecio)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoBotonCrearJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseExited
        // TODO add your handling code here:
        fondoBotonCrearJuego.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonCrearMouseExited

    private void botonCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseEntered
        // TODO add your handling code here:
        fondoBotonCrearJuego.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonCrearMouseEntered

    private void botonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseClicked
       
        Boolean puedeAgregarse=true;
        try{
            this.juego.setPrecio(Double.parseDouble(campoPrecio.getText()));
            if(Validar.juegoYaExiste(campoNombre.getText(), this.steam.getJuegos())){
                JOptionPane.showMessageDialog(this, "Juego ya existente");
                puedeAgregarse=false;
            }
            if(this.juego.getCategoria()==null){
                JOptionPane.showMessageDialog(this, "Seleccione categoria");
                puedeAgregarse=false;
            }else{
                this.juego.setNombre(campoNombre.getText());
                this.juego.setRutaVideo(campoLinkVideo.getText());
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Asegurese de que el precio contenga solo numeros");
            puedeAgregarse=false;
        }
        
        if(puedeAgregarse==true){
            steam.agregarJuego(juego);
            JOptionPane.showMessageDialog(this, "Juego creado exitosamente");
            this.juego=new Juego();
        }
    }//GEN-LAST:event_botonCrearMouseClicked

    private void botonAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAccionMouseClicked

        this.juego.setCategoria(EJuegos.ACCION.getCategoria());
        
    }//GEN-LAST:event_botonAccionMouseClicked

    private void botonAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAccionMouseEntered
 
        fondoBotonAccion.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAccionMouseEntered

    private void botonAccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAccionMouseExited
     
        fondoBotonAccion.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAccionMouseExited

    private void botonAventuraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAventuraMouseClicked
        // TODO add your handling code here:
        this.juego.setCategoria(EJuegos.AVENTURA.getCategoria());
    }//GEN-LAST:event_botonAventuraMouseClicked

    private void botonAventuraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAventuraMouseEntered
        // TODO add your handling code here:
        fondoBotonAventura.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAventuraMouseEntered

    private void botonAventuraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAventuraMouseExited
        // TODO add your handling code here:
        fondoBotonAventura.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonAventuraMouseExited

    private void botonDeRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeRolMouseClicked
        // TODO add your handling code here:
        this.juego.setCategoria(EJuegos.DEROL.getCategoria());
    }//GEN-LAST:event_botonDeRolMouseClicked

    private void botonDeRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeRolMouseEntered
        // TODO add your handling code here:
        fondoBotonDeRol.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonDeRolMouseEntered

    private void botonDeRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeRolMouseExited
        // TODO add your handling code here:
        fondoBotonDeRol.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonDeRolMouseExited

    private void botonSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSimulacionMouseClicked
        // TODO add your handling code here:
        this.juego.setCategoria(EJuegos.SIMULACION.getCategoria());
    }//GEN-LAST:event_botonSimulacionMouseClicked

    private void botonSimulacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSimulacionMouseEntered
        // TODO add your handling code here:
        fondoBotonSimulacion.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonSimulacionMouseEntered

    private void botonSimulacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSimulacionMouseExited
        // TODO add your handling code here:
        fondoBotonSimulacion.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonSimulacionMouseExited

    private void botonDeporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeporteMouseClicked
        // TODO add your handling code here:
        this.juego.setCategoria(EJuegos.DEPORTES.getCategoria());
    }//GEN-LAST:event_botonDeporteMouseClicked

    private void botonDeporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeporteMouseEntered
        // TODO add your handling code here:
        fondoBotonDeporte.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonDeporteMouseEntered

    private void botonDeporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeporteMouseExited
        // TODO add your handling code here:
        fondoBotonDeporte.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonDeporteMouseExited

    private void botonEstrategiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstrategiaMouseClicked
        // TODO add your handling code here:
        this.juego.setCategoria(EJuegos.ESTRATEGIA.getCategoria());
    }//GEN-LAST:event_botonEstrategiaMouseClicked

    private void botonEstrategiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstrategiaMouseEntered
        // TODO add your handling code here:
        fondoBotonEstrategia.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonEstrategiaMouseEntered

    private void botonEstrategiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstrategiaMouseExited
        // TODO add your handling code here:
        fondoBotonEstrategia.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonEstrategiaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraDeCategorias;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel botonAccion;
    private javax.swing.JLabel botonAventura;
    private javax.swing.JLabel botonCrear;
    private javax.swing.JLabel botonDeRol;
    private javax.swing.JLabel botonDeporte;
    private javax.swing.JLabel botonEstrategia;
    private javax.swing.JLabel botonSimulacion;
    private javax.swing.JTextField campoLinkVideo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JPanel fondoBotonAccion;
    private javax.swing.JPanel fondoBotonAventura;
    private javax.swing.JPanel fondoBotonCrearJuego;
    private javax.swing.JPanel fondoBotonDeRol;
    private javax.swing.JPanel fondoBotonDeporte;
    private javax.swing.JPanel fondoBotonEstrategia;
    private javax.swing.JPanel fondoBotonSimulacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel textoCategoria;
    private javax.swing.JLabel textoLinkVideo;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPrecio;
    private javax.swing.JLabel textoRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
