/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Cliente;
import Model.Clases.Steam;
import Model.Clases.UserBasico;
import Model.Clases.UsuarioPremium;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paola
 */
public class vistaReactivar extends javax.swing.JPanel {

    /**
     * Creates new form vistaReactivar
     */
    
    private Steam steam;
    private Cliente reactivar;
    
    public vistaReactivar(Steam steam) {
        this.steam=steam;
        initComponents();
        listarInactivos(steam.listarClientesDadosDeBaja());
        this.reactivar=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fondoReactivar = new javax.swing.JPanel();
        botonReactivar = new javax.swing.JLabel();
        textoUsuariosInactivos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Nickname", "Email", "Dni", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        fondoReactivar.setBackground(new java.awt.Color(153, 0, 255));

        botonReactivar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonReactivar.setForeground(new java.awt.Color(255, 255, 255));
        botonReactivar.setText("       Reactivar");
        botonReactivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReactivarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReactivarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReactivarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoReactivarLayout = new javax.swing.GroupLayout(fondoReactivar);
        fondoReactivar.setLayout(fondoReactivarLayout);
        fondoReactivarLayout.setHorizontalGroup(
            fondoReactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReactivar, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        fondoReactivarLayout.setVerticalGroup(
            fondoReactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReactivar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        textoUsuariosInactivos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoUsuariosInactivos.setForeground(new java.awt.Color(255, 255, 255));
        textoUsuariosInactivos.setText("Usuarios Inactivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(fondoReactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(textoUsuariosInactivos)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(textoUsuariosInactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(fondoReactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonReactivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseClicked
        // TODO add your handling code here:
        if(reactivar != null){
            reactivar.setActivo(true);
            if(reactivar instanceof UserBasico){
                steam.agregarUsuario((UserBasico) reactivar);
            }else{
                steam.agregarUsuarioPremimu((UsuarioPremium) reactivar);
            }
            JOptionPane.showMessageDialog(this,"Cliente reactivado");
            listarInactivos(steam.listarClientesDadosDeBaja());
        }else{
            JOptionPane.showMessageDialog(this,"Primero seleccione un cliente");
        }
    }//GEN-LAST:event_botonReactivarMouseClicked

    private void botonReactivarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseEntered
        // TODO add your handling code here:
        fondoReactivar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonReactivarMouseEntered

    private void botonReactivarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseExited
        // TODO add your handling code here:
        fondoReactivar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonReactivarMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        this.reactivar=this.steam.buscarClienteBasicoPorNickname(model.getValueAt(row, 1).toString());
        if(this.reactivar==null){
            this.reactivar=this.steam.buscarClienteBasicoPorNickname(model.getValueAt(row, 1).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked


    private void listarInactivos(ArrayList<Cliente> clientes){
        DefaultTableModel datos=(DefaultTableModel)jTable1.getModel();
        datos.setNumRows(0);
        String tipo="";
        for(Cliente cliente: clientes){
                if(cliente instanceof UserBasico){
                    tipo="Basico";
                }else{
                    tipo="Premium";
                }
                Object [] fila = {cliente.getNombre(),cliente.getNickName(),cliente.getMail(),cliente.getDni(),tipo};
                datos.addRow(fila);  
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonReactivar;
    private javax.swing.JPanel fondoReactivar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel textoUsuariosInactivos;
    // End of variables declaration//GEN-END:variables
}
