/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Admin;
import Model.Clases.Steam;
import Model.Clases.Validar;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author paola
 */
public class vistaCrearAdmin extends javax.swing.JPanel {

    public Steam steam;
    private Admin nuevo;
    /**
     * Creates new form vistaCrearAdmin
     */
    public vistaCrearAdmin(Steam steam) {
        this.steam=steam;
        nuevo=new Admin();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoNombre = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        textoRegistroUsuario = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoDni = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoContrasenia = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        textoApellido = new javax.swing.JLabel();
        textoDni = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoContrasenia = new javax.swing.JLabel();
        fondoBotonRegistrar = new javax.swing.JPanel();
        botonRegsitrar = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(822, 555));

        textoNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("                  Nombre:");

        barraSuperior.setBackground(new java.awt.Color(153, 0, 255));

        textoRegistroUsuario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoRegistroUsuario.setText("Registro de nuevo Admin");

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(textoRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoRegistroUsuario)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        campoNombre.setBackground(new java.awt.Color(51, 51, 51));
        campoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setBorder(null);

        campoApellido.setBackground(new java.awt.Color(51, 51, 51));
        campoApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoApellido.setForeground(new java.awt.Color(255, 255, 255));
        campoApellido.setBorder(null);

        campoDni.setBackground(new java.awt.Color(51, 51, 51));
        campoDni.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoDni.setForeground(new java.awt.Color(255, 255, 255));
        campoDni.setBorder(null);

        campoEmail.setBackground(new java.awt.Color(51, 51, 51));
        campoEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(255, 255, 255));
        campoEmail.setBorder(null);

        campoContrasenia.setBackground(new java.awt.Color(51, 51, 51));
        campoContrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        campoContrasenia.setBorder(null);

        textoApellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(255, 255, 255));
        textoApellido.setText("                  Apellido:");

        textoDni.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoDni.setForeground(new java.awt.Color(255, 255, 255));
        textoDni.setText("                          Dni:");

        textoEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoEmail.setForeground(new java.awt.Color(255, 255, 255));
        textoEmail.setText("                     E-Mail:");

        textoContrasenia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        textoContrasenia.setText("            Contraseña:");

        fondoBotonRegistrar.setBackground(new java.awt.Color(153, 0, 255));

        botonRegsitrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonRegsitrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegsitrar.setText("      Registrar");
        botonRegsitrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegsitrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegsitrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegsitrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegsitrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonRegistrarLayout = new javax.swing.GroupLayout(fondoBotonRegistrar);
        fondoBotonRegistrar.setLayout(fondoBotonRegistrarLayout);
        fondoBotonRegistrarLayout.setHorizontalGroup(
            fondoBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegsitrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        fondoBotonRegistrarLayout.setVerticalGroup(
            fondoBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegsitrar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoApellido)
                .addGap(12, 12, 12)
                .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoEmail)
                .addGap(13, 13, 13)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoContrasenia)
                .addGap(12, 12, 12)
                .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119)
                .addComponent(fondoBotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoApellido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDni)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEmail)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoContrasenia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(fondoBotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegsitrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonRegsitrarMouseExited

    private void botonRegsitrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonRegsitrarMouseEntered

    private void botonRegsitrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarMouseClicked
        // TODO add your handling code here:
        this.nuevo=new Admin();
        Boolean contraOK=false;
        Boolean mailOK=false;
        nuevo.setActivo(true);
        nuevo.setNombre(campoNombre.getText());
        nuevo.setApellido(campoApellido.getText());
        nuevo.setDni(campoDni.getText());
        ArrayList<Boolean> validacionContra=Validar.contrasena(campoContrasenia.getText());
        if(validacionContra.get(0)==true){
            this.nuevo.setContrasena(campoContrasenia.getText());
            contraOK=true;
        }else if(validacionContra.get(1)==false){
            JOptionPane.showConfirmDialog(this, "Debe contener al menos una mayuscula");
        }else if(validacionContra.get(2)==false){
            JOptionPane.showConfirmDialog(this, "Debe contener al menos un numero");
        }else if(validacionContra.get(3)==false){
            JOptionPane.showConfirmDialog(this, "Debe contener al menos ocho caracteres");
        }
        
        ArrayList<Boolean> validacionesMail=Validar.mailAdmin(campoEmail.getText(), this.steam.getUsuariosAdmins());
        if(validacionesMail.get(0)==true){
            this.nuevo.setMail(campoEmail.getText());
            mailOK=true;
        }else if(validacionesMail.get(1)==false){
            JOptionPane.showConfirmDialog(this, "El mail no continene @ o .com");
        }else if(validacionesMail.get(2)==false){
            JOptionPane.showConfirmDialog(this, "El mail ya se encuentra registrado en el sistema");
        }
        
        if(mailOK && contraOK){
            this.steam.agregarAdmin(nuevo);
            JOptionPane.showConfirmDialog(this, "Admin generado correctamente");
        }
           
    }//GEN-LAST:event_botonRegsitrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel botonRegsitrar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JPasswordField campoContrasenia;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel fondoBotonRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel textoApellido;
    private javax.swing.JLabel textoContrasenia;
    private javax.swing.JLabel textoDni;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
