/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Juego;
import Model.Clases.Steam;
import Model.Clases.UsuarioPremium;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paola
 */
public class vistaValorarJuegos extends javax.swing.JPanel {
    
    private UsuarioPremium usuario;
    private Juego aValorar;
    private Steam steam;
    
    /**
     * Creates new form vistaValorarJuegos
     */
    public vistaValorarJuegos(UsuarioPremium usuario,Steam steam){
        this.usuario=usuario;
        this.aValorar=null;
        this.steam=steam;
        initComponents();
        listarNoValorados(usuario.getComprados());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaJuego = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textoIngreseValoracion = new javax.swing.JLabel();
        campoValoracion = new javax.swing.JTextField();
        fondoValorar = new javax.swing.JPanel();
        textoValorar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        tablaJuego.setBackground(new java.awt.Color(51, 51, 51));
        tablaJuego.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tablaJuego.setViewportView(jTable1);

        textoIngreseValoracion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoIngreseValoracion.setForeground(new java.awt.Color(255, 255, 255));
        textoIngreseValoracion.setText("Ingrese la valoracion:");

        campoValoracion.setBackground(new java.awt.Color(51, 51, 51));
        campoValoracion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoValoracion.setForeground(new java.awt.Color(255, 255, 255));
        campoValoracion.setText("  1 al 5");

        fondoValorar.setBackground(new java.awt.Color(153, 0, 255));
        fondoValorar.setForeground(new java.awt.Color(153, 0, 255));

        textoValorar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoValorar.setForeground(new java.awt.Color(255, 255, 255));
        textoValorar.setText("       Valorar");
        textoValorar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoValorarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoValorarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoValorarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoValorarLayout = new javax.swing.GroupLayout(fondoValorar);
        fondoValorar.setLayout(fondoValorarLayout);
        fondoValorarLayout.setHorizontalGroup(
            fondoValorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
            .addGroup(fondoValorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoValorarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoValorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        fondoValorarLayout.setVerticalGroup(
            fondoValorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(fondoValorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoValorarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoValorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(fondoValorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(tablaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(textoIngreseValoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoIngreseValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(fondoValorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(tablaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoValorarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoValorarMouseClicked
        if(aValorar!=null){
            Double valoracion=Double.parseDouble(campoValoracion.getText());
            aValorar.setCantValoraciones(aValorar.getCantValoraciones()+1);
            Double nuevaVal=(Double) ((aValorar.getValoracion()+valoracion)/aValorar.getCantValoraciones());
            aValorar.setValoracion(nuevaVal);
            this.steam.reemplazaJuego(aValorar);
            this.usuario.getValorados().add(aValorar.getIdJuego());
            listarNoValorados(usuario.getComprados());
            JOptionPane.showMessageDialog(this, "Valorado correctamente con un " + valoracion);

        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un juego");
        }
    }//GEN-LAST:event_textoValorarMouseClicked

    private void textoValorarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoValorarMouseEntered
        // TODO add your handling code here:
        textoValorar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoValorarMouseEntered

    private void textoValorarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoValorarMouseExited
        // TODO add your handling code here:
        textoValorar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoValorarMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        this.aValorar=this.steam.retornaJuego(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void listarNoValorados(ArrayList<Juego> juegos){
        DefaultTableModel datos=(DefaultTableModel)jTable1.getModel();
        datos.setNumRows(0);
        for(Juego juego: juegos){
                if(!this.usuario.getValorados().contains(juego.getIdJuego())){
                    Object [] fila = {juego.getNombre(),juego.getCategoria()};
                    datos.addRow(fila);
                }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoValoracion;
    private javax.swing.JPanel fondoValorar;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tablaJuego;
    private javax.swing.JLabel textoIngreseValoracion;
    private javax.swing.JLabel textoValorar;
    // End of variables declaration//GEN-END:variables
}
