/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Model.Clases.Cliente;
import Model.Clases.Juego;
import Model.Clases.MovimientoEconomico;
import Model.Clases.MovimientoEconomico.tipoDeMovimiento;
import Model.Clases.Pedido;
import Model.Clases.Steam;
import Model.Enums.EJuegos;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paola
 */
public class vistaComprar extends javax.swing.JPanel {
    
    private Steam steam;
    private Cliente cliente;
    private Pedido pedido;

    /**
     * Creates new form vistaComprar
     */
    public vistaComprar(Steam steam,Cliente cliente) {
        this.steam=steam;
        this.cliente=cliente;
        this.pedido=new Pedido();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondoBarraSuperior = new javax.swing.JPanel();
        fondoPanelAccion = new javax.swing.JPanel();
        textoAccion = new javax.swing.JLabel();
        fondoPanelAventura = new javax.swing.JPanel();
        textoAventura = new javax.swing.JLabel();
        fondoPanelDeRol = new javax.swing.JPanel();
        textoDeRol = new javax.swing.JLabel();
        fondoPanelSimulacion = new javax.swing.JPanel();
        textoSimulacion = new javax.swing.JLabel();
        fondoPanelDeportes = new javax.swing.JPanel();
        textoDeportes = new javax.swing.JLabel();
        fondoPanelEstrategia = new javax.swing.JPanel();
        textoEstrategia = new javax.swing.JLabel();
        tablaDeJuegos = new javax.swing.JScrollPane();
        tablaJuegos = new javax.swing.JTable();
        tablaDeCarrito = new javax.swing.JScrollPane();
        tablaPedido = new javax.swing.JTable();
        muestraTotalCarrito = new javax.swing.JLabel();
        fondoBotonComprar = new javax.swing.JPanel();
        botonComprar = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        fondoBarraSuperior.setBackground(new java.awt.Color(153, 0, 255));

        fondoPanelAccion.setBackground(new java.awt.Color(153, 0, 255));

        textoAccion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoAccion.setForeground(new java.awt.Color(255, 255, 255));
        textoAccion.setText("    Accion");
        textoAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoAccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoAccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelAccionLayout = new javax.swing.GroupLayout(fondoPanelAccion);
        fondoPanelAccion.setLayout(fondoPanelAccionLayout);
        fondoPanelAccionLayout.setHorizontalGroup(
            fondoPanelAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelAccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoPanelAccionLayout.setVerticalGroup(
            fondoPanelAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondoPanelAventura.setBackground(new java.awt.Color(153, 0, 255));

        textoAventura.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoAventura.setForeground(new java.awt.Color(255, 255, 255));
        textoAventura.setText("   Aventura");
        textoAventura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoAventuraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoAventuraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoAventuraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelAventuraLayout = new javax.swing.GroupLayout(fondoPanelAventura);
        fondoPanelAventura.setLayout(fondoPanelAventuraLayout);
        fondoPanelAventuraLayout.setHorizontalGroup(
            fondoPanelAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoPanelAventuraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoAventura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoPanelAventuraLayout.setVerticalGroup(
            fondoPanelAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelAventuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textoAventura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        fondoPanelDeRol.setBackground(new java.awt.Color(153, 0, 255));

        textoDeRol.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoDeRol.setForeground(new java.awt.Color(255, 255, 255));
        textoDeRol.setText("      De Rol");
        textoDeRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoDeRolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoDeRolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoDeRolMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelDeRolLayout = new javax.swing.GroupLayout(fondoPanelDeRol);
        fondoPanelDeRol.setLayout(fondoPanelDeRolLayout);
        fondoPanelDeRolLayout.setHorizontalGroup(
            fondoPanelDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoPanelDeRolLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoDeRol, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoPanelDeRolLayout.setVerticalGroup(
            fondoPanelDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelDeRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textoDeRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        fondoPanelSimulacion.setBackground(new java.awt.Color(153, 0, 255));

        textoSimulacion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        textoSimulacion.setText("  Simulacion");
        textoSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoSimulacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoSimulacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoSimulacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelSimulacionLayout = new javax.swing.GroupLayout(fondoPanelSimulacion);
        fondoPanelSimulacion.setLayout(fondoPanelSimulacionLayout);
        fondoPanelSimulacionLayout.setHorizontalGroup(
            fondoPanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoPanelSimulacionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoPanelSimulacionLayout.setVerticalGroup(
            fondoPanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textoSimulacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        fondoPanelDeportes.setBackground(new java.awt.Color(153, 0, 255));

        textoDeportes.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoDeportes.setForeground(new java.awt.Color(255, 255, 255));
        textoDeportes.setText("    Deportes");
        textoDeportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoDeportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoDeportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoDeportesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelDeportesLayout = new javax.swing.GroupLayout(fondoPanelDeportes);
        fondoPanelDeportes.setLayout(fondoPanelDeportesLayout);
        fondoPanelDeportesLayout.setHorizontalGroup(
            fondoPanelDeportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelDeportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoPanelDeportesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textoDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoPanelDeportesLayout.setVerticalGroup(
            fondoPanelDeportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(fondoPanelDeportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textoDeportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        fondoPanelEstrategia.setBackground(new java.awt.Color(153, 0, 255));

        textoEstrategia.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoEstrategia.setForeground(new java.awt.Color(255, 255, 255));
        textoEstrategia.setText("  Estrategia");
        textoEstrategia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoEstrategiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoEstrategiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoEstrategiaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoPanelEstrategiaLayout = new javax.swing.GroupLayout(fondoPanelEstrategia);
        fondoPanelEstrategia.setLayout(fondoPanelEstrategiaLayout);
        fondoPanelEstrategiaLayout.setHorizontalGroup(
            fondoPanelEstrategiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelEstrategiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoPanelEstrategiaLayout.setVerticalGroup(
            fondoPanelEstrategiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelEstrategiaLayout.createSequentialGroup()
                .addComponent(textoEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoBarraSuperiorLayout = new javax.swing.GroupLayout(fondoBarraSuperior);
        fondoBarraSuperior.setLayout(fondoBarraSuperiorLayout);
        fondoBarraSuperiorLayout.setHorizontalGroup(
            fondoBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBarraSuperiorLayout.createSequentialGroup()
                .addComponent(fondoPanelAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoPanelAventura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoPanelDeRol, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fondoPanelSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoPanelDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondoPanelEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fondoBarraSuperiorLayout.setVerticalGroup(
            fondoBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPanelAventura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPanelDeRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPanelSimulacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPanelDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoPanelEstrategia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tablaJuegos.setBackground(new java.awt.Color(51, 51, 51));
        tablaJuegos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tablaJuegos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tablaJuegos.setForeground(new java.awt.Color(255, 255, 255));
        tablaJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio $", "Valoracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJuegosMouseClicked(evt);
            }
        });
        tablaDeJuegos.setViewportView(tablaJuegos);

        tablaDeCarrito.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        tablaPedido.setBackground(new java.awt.Color(51, 51, 51));
        tablaPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tablaPedido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tablaPedido.setForeground(new java.awt.Color(255, 255, 255));
        tablaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPedidoMouseClicked(evt);
            }
        });
        tablaDeCarrito.setViewportView(tablaPedido);

        muestraTotalCarrito.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        muestraTotalCarrito.setForeground(new java.awt.Color(255, 255, 255));
        muestraTotalCarrito.setText("Total: ${Total}");

        fondoBotonComprar.setBackground(new java.awt.Color(153, 0, 255));
        fondoBotonComprar.setForeground(new java.awt.Color(255, 255, 255));

        botonComprar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonComprar.setForeground(new java.awt.Color(255, 255, 255));
        botonComprar.setText(" Comprar");
        botonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonComprarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonComprarLayout = new javax.swing.GroupLayout(fondoBotonComprar);
        fondoBotonComprar.setLayout(fondoBotonComprarLayout);
        fondoBotonComprarLayout.setHorizontalGroup(
            fondoBotonComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
            .addGroup(fondoBotonComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoBotonComprarLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(botonComprar)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        fondoBotonComprarLayout.setVerticalGroup(
            fondoBotonComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(fondoBotonComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoBotonComprarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoBarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tablaDeJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaDeCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(muestraTotalCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(fondoBotonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondoBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tablaDeCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fondoBotonComprar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(muestraTotalCarrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tablaDeJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAccionMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.ACCION.getCategoria());
    }//GEN-LAST:event_textoAccionMouseClicked

    private void textoAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAccionMouseEntered
        // TODO add your handling code here:
        fondoPanelAccion.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoAccionMouseEntered

    private void textoAccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAccionMouseExited
        // TODO add your handling code here:
        fondoPanelAccion.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoAccionMouseExited

    private void textoAventuraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAventuraMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.AVENTURA.getCategoria());
    }//GEN-LAST:event_textoAventuraMouseClicked

    private void textoAventuraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAventuraMouseEntered
        // TODO add your handling code here:
        fondoPanelAventura.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoAventuraMouseEntered

    private void textoAventuraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoAventuraMouseExited
        // TODO add your handling code here:
        fondoPanelAventura.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoAventuraMouseExited

    private void textoDeRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeRolMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.DEROL.getCategoria());
    }//GEN-LAST:event_textoDeRolMouseClicked

    private void textoDeRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeRolMouseEntered
        // TODO add your handling code here:
        fondoPanelDeRol.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoDeRolMouseEntered

    private void textoDeRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeRolMouseExited
        // TODO add your handling code here:
        fondoPanelDeRol.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoDeRolMouseExited

    private void textoSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoSimulacionMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.SIMULACION.getCategoria());
    }//GEN-LAST:event_textoSimulacionMouseClicked

    private void textoSimulacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoSimulacionMouseEntered
        // TODO add your handling code here:
        fondoPanelSimulacion.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoSimulacionMouseEntered

    private void textoSimulacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoSimulacionMouseExited
        // TODO add your handling code here:
        fondoPanelSimulacion.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoSimulacionMouseExited

    private void textoDeportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeportesMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.DEPORTES.getCategoria());
    }//GEN-LAST:event_textoDeportesMouseClicked

    private void textoDeportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeportesMouseEntered
        // TODO add your handling code here:
        fondoPanelDeportes.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoDeportesMouseEntered

    private void textoDeportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDeportesMouseExited
        // TODO add your handling code here:
        fondoPanelDeportes.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoDeportesMouseExited

    private void textoEstrategiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEstrategiaMouseClicked
        // TODO add your handling code here:
        listarPorCategoria(EJuegos.ESTRATEGIA.getCategoria());
    }//GEN-LAST:event_textoEstrategiaMouseClicked

    private void textoEstrategiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEstrategiaMouseEntered
        // TODO add your handling code here:
        fondoPanelEstrategia.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_textoEstrategiaMouseEntered

    private void textoEstrategiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEstrategiaMouseExited
        // TODO add your handling code here:
        fondoPanelEstrategia.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_textoEstrategiaMouseExited

    private void botonComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseClicked
        // TODO add your handling code here:
        this.pedido.setCliente(this.cliente.getId());
        steam.agregarPedido(pedido);
        cliente.agregarMovimientoEconomico(new MovimientoEconomico(tipoDeMovimiento.SALIDA,pedido.getValorTotal()));
        cliente.comprar(pedido);
        cliente.setSaldo(cliente.getSaldo()-pedido.getValorTotal());
        this.pedido=new Pedido();
        listarPedido();
        JOptionPane.showMessageDialog(this,"Compra realizada correctamente");
    }//GEN-LAST:event_botonComprarMouseClicked

    private void botonComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseEntered
        // TODO add your handling code here:
        fondoBotonComprar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonComprarMouseEntered

    private void botonComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseExited
        // TODO add your handling code here:
        fondoBotonComprar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonComprarMouseExited

    private void tablaJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuegosMouseClicked
        //agrega el juego al pedido cuando lo seleccionamos
        int row=tablaJuegos.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)tablaJuegos.getModel();
        Juego agregar=this.steam.retornaJuego(model.getValueAt(row, 0).toString());
        if(this.pedido.getJuegos().contains(agregar)){
            JOptionPane.showMessageDialog(this,"Usted ya ha agregado este juego a su pedido");
        }else{
            this.pedido.getJuegos().add(agregar);
            this.pedido.setValorTotal(this.pedido.getValorTotal()+agregar.getPrecio());
            this.muestraTotalCarrito.setText("Total: $"+this.pedido.getValorTotal().toString());
            listarPedido();
        }

    }//GEN-LAST:event_tablaJuegosMouseClicked

    private void tablaPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPedidoMouseClicked
        // elimina el juego del pedido cuando lo seleccionamos
        int row=tablaPedido.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)tablaPedido.getModel();
        this.pedido.setValorTotal(this.pedido.getValorTotal()-this.steam.retornaJuego(model.getValueAt(row, 0).toString()).getPrecio());
        this.pedido.getJuegos().remove(this.steam.retornaJuego(model.getValueAt(row, 0).toString()));
        this.muestraTotalCarrito.setText("Total: $"+this.pedido.getValorTotal().toString());
        listarPedido();
    }//GEN-LAST:event_tablaPedidoMouseClicked

    private void listarPorCategoria(String categoria){
        //Agrega los juegos a la tabla teniendo en cuenta que sean de la categoria que se envia por parametro
        DefaultTableModel datos=(DefaultTableModel)tablaJuegos.getModel();
        datos.setNumRows(0);
        for(Juego juego: this.steam.getJuegos()){
            if(juego.getCategoria().equals(categoria) && !cliente.getComprados().contains(juego)){
                Object [] fila = {juego.getNombre(),juego.getPrecio(),juego.getValoracion()};
                datos.addRow(fila);
            }
        }
    }
    
    private void listarPedido(){
        DefaultTableModel datos=(DefaultTableModel)tablaPedido.getModel();
        datos.setNumRows(0);
        for(Juego juego: this.pedido.getJuegos()){
                Object [] fila = {juego.getNombre(),juego.getCategoria(),juego.getPrecio()};
                datos.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonComprar;
    private javax.swing.JPanel fondoBarraSuperior;
    private javax.swing.JPanel fondoBotonComprar;
    private javax.swing.JPanel fondoPanelAccion;
    private javax.swing.JPanel fondoPanelAventura;
    private javax.swing.JPanel fondoPanelDeRol;
    private javax.swing.JPanel fondoPanelDeportes;
    private javax.swing.JPanel fondoPanelEstrategia;
    private javax.swing.JPanel fondoPanelSimulacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel muestraTotalCarrito;
    private javax.swing.JScrollPane tablaDeCarrito;
    private javax.swing.JScrollPane tablaDeJuegos;
    private javax.swing.JTable tablaJuegos;
    private javax.swing.JTable tablaPedido;
    private javax.swing.JLabel textoAccion;
    private javax.swing.JLabel textoAventura;
    private javax.swing.JLabel textoDeRol;
    private javax.swing.JLabel textoDeportes;
    private javax.swing.JLabel textoEstrategia;
    private javax.swing.JLabel textoSimulacion;
    // End of variables declaration//GEN-END:variables
}
