/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUISS;

import Model.Clases.Admin;
import Model.Clases.Steam;
import Model.Clases.UserBasico;
import Model.Clases.Usuario;
import Model.Clases.UsuarioPremium;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.swing.JOptionPane;
import java.io.File;

/**
 *
 * @author paola
 */
public class LogIn extends javax.swing.JFrame {
    
    private Steam steam;
    private Usuario user;
    private ObjectMapper mapper;
    private File file;
    /**
     * Creates new form LogIn
     */
    
    public LogIn(Steam steam,ObjectMapper mapper,File file){
        this.steam=steam;
        this.user=null;
        this.mapper=mapper;
        this.file=file;
        initComponents();
    }

    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDashBoard = new javax.swing.JPanel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        ingresoUser = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanelFondoIngresar = new javax.swing.JPanel();
        jLabelIngresar = new javax.swing.JLabel();
        jPanelFondoRegistrar = new javax.swing.JPanel();
        jLabelRegsitrarse = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTextoUsuario = new javax.swing.JLabel();
        jLabelTextoContrasenia = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelFotoSteam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanelDashBoard.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDashBoard.setForeground(new java.awt.Color(51, 51, 51));

        jLabelBienvenido.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenido.setText("Bienvenido");

        jLabelIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIniciarSesion.setText("Iniciar Sesion");

        ingresoUser.setBackground(new java.awt.Color(51, 51, 51));
        ingresoUser.setForeground(new java.awt.Color(255, 255, 255));
        ingresoUser.setBorder(null);

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jPanelFondoIngresar.setBackground(new java.awt.Color(153, 0, 255));
        jPanelFondoIngresar.setForeground(new java.awt.Color(255, 255, 255));

        jLabelIngresar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresar.setText("       INGRESAR");
        jLabelIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIngresarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoIngresarLayout = new javax.swing.GroupLayout(jPanelFondoIngresar);
        jPanelFondoIngresar.setLayout(jPanelFondoIngresarLayout);
        jPanelFondoIngresarLayout.setHorizontalGroup(
            jPanelFondoIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoIngresarLayout.setVerticalGroup(
            jPanelFondoIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoRegistrar.setBackground(new java.awt.Color(153, 0, 255));

        jLabelRegsitrarse.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelRegsitrarse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegsitrarse.setText("   REGISTRARSE");
        jLabelRegsitrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegsitrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegsitrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoRegistrarLayout = new javax.swing.GroupLayout(jPanelFondoRegistrar);
        jPanelFondoRegistrar.setLayout(jPanelFondoRegistrarLayout);
        jPanelFondoRegistrarLayout.setHorizontalGroup(
            jPanelFondoRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegsitrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoRegistrarLayout.setVerticalGroup(
            jPanelFondoRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegsitrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTextoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelTextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoUsuario.setText("Usuario");

        jLabelTextoContrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelTextoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoContrasenia.setText("Contraseña");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDashBoardLayout = new javax.swing.GroupLayout(jPanelDashBoard);
        jPanelDashBoard.setLayout(jPanelDashBoardLayout);
        jPanelDashBoardLayout.setHorizontalGroup(
            jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashBoardLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashBoardLayout.createSequentialGroup()
                        .addGroup(jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTextoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ingresoUser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelFondoIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelFondoRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashBoardLayout.createSequentialGroup()
                        .addComponent(jLabelIniciarSesion)
                        .addGap(55, 55, 55))))
        );
        jPanelDashBoardLayout.setVerticalGroup(
            jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashBoardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTextoContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanelFondoIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanelFondoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabelFotoSteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Captura de pantalla 2023-05-22 194112.jpg"))); // NOI18N
        jLabelFotoSteam.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFotoSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelFotoSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabelIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresarMouseClicked
        // TODO add your handling code here: este llama a las verificaciones, si es correcto ingresa, sino printea que la contrasenia es incorrecta
        user=steam.buscarClienteBasicoPorNickname(ingresoUser.getText());
        if(user!=null){
            if(!user.getContrasena().equals(jPasswordField1.getText())){
                JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
            }else if(user.getActivo()==false){
                JOptionPane.showMessageDialog(this,"Usuario dado de baja, contactese con un admin");
            }else{
                MenuPrincipalUserBasico menuBasico = new MenuPrincipalUserBasico(this, this.steam, (UserBasico) user,this.file,this.mapper);
                menuBasico.setVisible(true);
            }
        }else if (user == null){
            user=this.steam.buscarClientePremiumPorNickname(ingresoUser.getText());
            if(user!=null){
                if(!user.getContrasena().equals(jPasswordField1.getText())){
                    JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
                }else if (user.getActivo()==false){
                    JOptionPane.showMessageDialog(this,"Usuario dado de baja, contactese con un admin");
                }else {
                    MenuPrincipalUserPremium menuPremium = new MenuPrincipalUserPremium(this, this.steam, (UsuarioPremium) user,this.file,this.mapper);
                    menuPremium.setVisible(true);
                }
            }
        }

        if(user==null){
            user=steam.buscarAdminPorNombre(ingresoUser.getText());
        }
        
        if(user == null){
            JOptionPane.showMessageDialog(null,"Usuario no encontrado");
        }else if(user instanceof Admin){
            if(!user.getContrasena().equals(jPasswordField1.getText())){
                JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
            }else if (user.getActivo()==false){
                JOptionPane.showMessageDialog(this,"Usuario dado de baja, contactese con un admin");
            }else {
                MenuPrincipalAdmin menuAdmin = new MenuPrincipalAdmin(this, this.steam, (Admin) user,this.file,this.mapper);
                menuAdmin.setVisible(true);
            }
        }

        if(user!=null){
            if(user.getActivo()==true){
                dispose();
            }
        }


        
    }//GEN-LAST:event_jLabelIngresarMouseClicked

    private void jLabelRegsitrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegsitrarseMouseClicked
        // TODO add your handling code here: este envia al formulario para registrarse
        MenuRegistroUser registro= new MenuRegistroUser(this,steam,this.file,this.mapper);
        registro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelRegsitrarseMouseClicked

    private void jLabelIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelIngresarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresoUser;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelFotoSteam;
    private javax.swing.JLabel jLabelIngresar;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelRegsitrarse;
    private javax.swing.JLabel jLabelTextoContrasenia;
    private javax.swing.JLabel jLabelTextoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDashBoard;
    private javax.swing.JPanel jPanelFondoIngresar;
    private javax.swing.JPanel jPanelFondoRegistrar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
