/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUISS;

import Model.Clases.Admin;
import Model.Clases.Steam;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JPanel;

import com.fasterxml.jackson.databind.ObjectMapper;
import vistas.vistaAjustes;
import vistas.vistaAjustesAdmin;
import vistas.vistaCargarSaldo;
import vistas.vistaCrearAdmin;
import vistas.vistaCrearJuego;
import vistas.vistaJugar;
import vistas.vistaDeInicioAdmin;
import vistas.vistaEliminarUsuario;
import vistas.vistaJugar;
import vistas.vistaListarJuegos;
import vistas.vistaListarUsers;
import vistas.vistaMensajes;
import vistas.vistaReactivar;

/**
 *
 * @author paola
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalUserBasico
     */
    
    private LogIn lw;
    private Steam steam;
    private Admin admin;
    private File file;
    private ObjectMapper mapper;
    
    public MenuPrincipalAdmin(LogIn lw,Steam steam,Admin admin,File file,ObjectMapper mapper) {
        this.lw=lw;
        this.admin=admin;
        this.steam=steam;
        this.file=file;
        this.mapper=mapper;
        initComponents();
        initContenido();
        setBienvenida();
        setDate();
    }

    private MenuPrincipalAdmin() {
        
    }
    
    private void setBienvenida(){
        textoBienvenida.setText("Bienvenido "+admin.getNombre()+" "+admin.getApellido()+" !");
    }
    
    private void setDate(){
    LocalDate now= LocalDate.now();
    int year=now.getYear();
    int dia=now.getDayOfMonth();
    int month=now.getMonthValue();
    String[] meses={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
    textoFecha.setText("Hoy es "+dia+" de "+meses[month-1]+" de " +year);
    
    }
    
    private void initContenido(){
        ShowJPanel(new vistaDeInicioAdmin(this.steam));
    }
    
    private void ShowJPanel(JPanel p){
        p.setSize(882,404);
        p.setLocation(0,0);
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jPanelFondoInicio = new javax.swing.JPanel();
        botonInicio = new javax.swing.JLabel();
        jPanelFondoListarUsuarios = new javax.swing.JPanel();
        botonListarUsuarios = new javax.swing.JLabel();
        jPanelFondoListarJuegos = new javax.swing.JPanel();
        botonListarJuegos = new javax.swing.JLabel();
        jPanelFondoEliminarUsuarios = new javax.swing.JPanel();
        botonEliminarUsuario = new javax.swing.JLabel();
        jPanelFondoCrearAdmin = new javax.swing.JPanel();
        botonCrearAdmin = new javax.swing.JLabel();
        jPanelFondoCrearJuego = new javax.swing.JPanel();
        botonCrearJuego = new javax.swing.JLabel();
        jPanelFondoAjustes = new javax.swing.JPanel();
        botonAjustes = new javax.swing.JLabel();
        jPanelFondoSalir = new javax.swing.JPanel();
        botonSalir = new javax.swing.JLabel();
        fondoReactivar = new javax.swing.JPanel();
        botonReactivar = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        textoBienvenida = new javax.swing.JLabel();
        textoFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(51, 51, 51));

        menu.setBackground(new java.awt.Color(153, 0, 255));

        jPanelFondoInicio.setBackground(new java.awt.Color(153, 0, 255));

        botonInicio.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("           Inicio");
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoInicioLayout = new javax.swing.GroupLayout(jPanelFondoInicio);
        jPanelFondoInicio.setLayout(jPanelFondoInicioLayout);
        jPanelFondoInicioLayout.setHorizontalGroup(
            jPanelFondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoInicioLayout.setVerticalGroup(
            jPanelFondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoListarUsuarios.setBackground(new java.awt.Color(153, 0, 255));

        botonListarUsuarios.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonListarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonListarUsuarios.setText(" Listar Usuarios");
        botonListarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonListarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListarUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonListarUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonListarUsuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoListarUsuariosLayout = new javax.swing.GroupLayout(jPanelFondoListarUsuarios);
        jPanelFondoListarUsuarios.setLayout(jPanelFondoListarUsuariosLayout);
        jPanelFondoListarUsuariosLayout.setHorizontalGroup(
            jPanelFondoListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoListarUsuariosLayout.setVerticalGroup(
            jPanelFondoListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoListarJuegos.setBackground(new java.awt.Color(153, 0, 255));

        botonListarJuegos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonListarJuegos.setForeground(new java.awt.Color(255, 255, 255));
        botonListarJuegos.setText("  Listar Juegos");
        botonListarJuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonListarJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListarJuegosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonListarJuegosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonListarJuegosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoListarJuegosLayout = new javax.swing.GroupLayout(jPanelFondoListarJuegos);
        jPanelFondoListarJuegos.setLayout(jPanelFondoListarJuegosLayout);
        jPanelFondoListarJuegosLayout.setHorizontalGroup(
            jPanelFondoListarJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonListarJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoListarJuegosLayout.setVerticalGroup(
            jPanelFondoListarJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonListarJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoEliminarUsuarios.setBackground(new java.awt.Color(153, 0, 255));

        botonEliminarUsuario.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        botonEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarUsuario.setText(" Eliminar Usuarios");
        botonEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoEliminarUsuariosLayout = new javax.swing.GroupLayout(jPanelFondoEliminarUsuarios);
        jPanelFondoEliminarUsuarios.setLayout(jPanelFondoEliminarUsuariosLayout);
        jPanelFondoEliminarUsuariosLayout.setHorizontalGroup(
            jPanelFondoEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoEliminarUsuariosLayout.setVerticalGroup(
            jPanelFondoEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoCrearAdmin.setBackground(new java.awt.Color(153, 0, 255));

        botonCrearAdmin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonCrearAdmin.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearAdmin.setText("    Crear Admin");
        botonCrearAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrearAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCrearAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCrearAdminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoCrearAdminLayout = new javax.swing.GroupLayout(jPanelFondoCrearAdmin);
        jPanelFondoCrearAdmin.setLayout(jPanelFondoCrearAdminLayout);
        jPanelFondoCrearAdminLayout.setHorizontalGroup(
            jPanelFondoCrearAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCrearAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoCrearAdminLayout.setVerticalGroup(
            jPanelFondoCrearAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCrearAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoCrearJuego.setBackground(new java.awt.Color(153, 0, 255));

        botonCrearJuego.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonCrearJuego.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearJuego.setText("    Crear Juego");
        botonCrearJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrearJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearJuegoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCrearJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCrearJuegoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoCrearJuegoLayout = new javax.swing.GroupLayout(jPanelFondoCrearJuego);
        jPanelFondoCrearJuego.setLayout(jPanelFondoCrearJuegoLayout);
        jPanelFondoCrearJuegoLayout.setHorizontalGroup(
            jPanelFondoCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCrearJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoCrearJuegoLayout.setVerticalGroup(
            jPanelFondoCrearJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCrearJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoAjustes.setBackground(new java.awt.Color(153, 0, 255));

        botonAjustes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonAjustes.setForeground(new java.awt.Color(255, 255, 255));
        botonAjustes.setText("        Ajustes");
        botonAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAjustesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAjustesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoAjustesLayout = new javax.swing.GroupLayout(jPanelFondoAjustes);
        jPanelFondoAjustes.setLayout(jPanelFondoAjustesLayout);
        jPanelFondoAjustesLayout.setHorizontalGroup(
            jPanelFondoAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoAjustesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFondoAjustesLayout.setVerticalGroup(
            jPanelFondoAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoAjustesLayout.createSequentialGroup()
                .addComponent(botonAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelFondoSalir.setBackground(new java.awt.Color(153, 0, 255));

        botonSalir.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("            Salir");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoSalirLayout = new javax.swing.GroupLayout(jPanelFondoSalir);
        jPanelFondoSalir.setLayout(jPanelFondoSalirLayout);
        jPanelFondoSalirLayout.setHorizontalGroup(
            jPanelFondoSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoSalirLayout.setVerticalGroup(
            jPanelFondoSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoSalirLayout.createSequentialGroup()
                .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoReactivar.setBackground(new java.awt.Color(153, 0, 255));
        fondoReactivar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        botonReactivar.setBackground(new java.awt.Color(153, 0, 255));
        botonReactivar.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        botonReactivar.setForeground(new java.awt.Color(255, 255, 255));
        botonReactivar.setText("Reactivar usuarios");
        botonReactivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReactivarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReactivarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReactivarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoReactivarLayout = new javax.swing.GroupLayout(fondoReactivar);
        fondoReactivar.setLayout(fondoReactivarLayout);
        fondoReactivarLayout.setHorizontalGroup(
            fondoReactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoReactivarLayout.setVerticalGroup(
            fondoReactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReactivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoListarJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoEliminarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoCrearAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoCrearJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondoReactivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelFondoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoListarJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoCrearAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoCrearJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondoReactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelFondoAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFondoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/store_home_share.jpg"))); // NOI18N
        header.setText("jLabel12");

        contenido.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textoBienvenida.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        textoBienvenida.setText("Bienvenido {nickname} !");

        textoFecha.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoFecha.setForeground(new java.awt.Color(255, 255, 255));
        textoFecha.setText("Hoy es {dia} de {mes} del {anio}");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 355, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarUsuariosMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaListarUsers(this.steam));
    }//GEN-LAST:event_botonListarUsuariosMouseClicked

    private void botonListarUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarUsuariosMouseEntered
        // TODO add your handling code here:
        jPanelFondoListarUsuarios.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonListarUsuariosMouseEntered

    private void botonListarUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarUsuariosMouseExited
        // TODO add your handling code here:
        jPanelFondoListarUsuarios.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonListarUsuariosMouseExited

    private void botonListarJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarJuegosMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaListarJuegos(this.steam.getJuegos()));
    }//GEN-LAST:event_botonListarJuegosMouseClicked

    private void botonListarJuegosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarJuegosMouseEntered
        // TODO add your handling code here:
        jPanelFondoListarJuegos.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonListarJuegosMouseEntered

    private void botonListarJuegosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarJuegosMouseExited
        // TODO add your handling code here:
        jPanelFondoListarJuegos.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonListarJuegosMouseExited

    private void botonEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaEliminarUsuario(this.steam));
    }//GEN-LAST:event_botonEliminarUsuarioMouseClicked

    private void botonEliminarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioMouseEntered
        // TODO add your handling code here:
        jPanelFondoEliminarUsuarios.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonEliminarUsuarioMouseEntered

    private void botonEliminarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioMouseExited
        // TODO add your handling code here:
        jPanelFondoEliminarUsuarios.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonEliminarUsuarioMouseExited

    private void botonCrearAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearAdminMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaCrearAdmin(this.steam));
    }//GEN-LAST:event_botonCrearAdminMouseClicked

    private void botonCrearAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearAdminMouseEntered
        // TODO add your handling code here:
        jPanelFondoCrearAdmin.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonCrearAdminMouseEntered

    private void botonCrearAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearAdminMouseExited
        // TODO add your handling code here:
        jPanelFondoCrearAdmin.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonCrearAdminMouseExited

    private void botonCrearJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearJuegoMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaCrearJuego(this.steam));
    }//GEN-LAST:event_botonCrearJuegoMouseClicked

    private void botonCrearJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearJuegoMouseEntered
        // TODO add your handling code here:
        jPanelFondoCrearJuego.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonCrearJuegoMouseEntered

    private void botonCrearJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearJuegoMouseExited
        // TODO add your handling code here:
        jPanelFondoCrearJuego.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonCrearJuegoMouseExited

    private void botonAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseClicked
        // TODO add your handling code here:
        vistaAjustesAdmin ajustes=new vistaAjustesAdmin(this.steam,this.admin,this.mapper,this.file,this,this.lw);
        ShowJPanel(ajustes);
        
    }//GEN-LAST:event_botonAjustesMouseClicked

    private void botonAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseEntered
        // TODO add your handling code here:
        jPanelFondoAjustes.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAjustesMouseEntered

    private void botonAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseExited
        // TODO add your handling code here:
        jPanelFondoAjustes.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonAjustesMouseExited

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        // TODO add your handling code here:
        try {
            this.mapper.writerWithDefaultPrettyPrinter().writeValue(this.file,this.steam);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        lw.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
        jPanelFondoSalir.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
        jPanelFondoSalir.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited
        // TODO add your handling code here:
        jPanelFondoInicio.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonInicioMouseExited

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered
        // TODO add your handling code here:
        jPanelFondoInicio.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaDeInicioAdmin(this.steam));
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonReactivarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseEntered
        // TODO add your handling code here:
        fondoReactivar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonReactivarMouseEntered

    private void botonReactivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaReactivar(this.steam));
    }//GEN-LAST:event_botonReactivarMouseClicked

    private void botonReactivarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReactivarMouseExited
        // TODO add your handling code here:
        fondoReactivar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonReactivarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonAjustes;
    private javax.swing.JLabel botonCrearAdmin;
    private javax.swing.JLabel botonCrearJuego;
    private javax.swing.JLabel botonEliminarUsuario;
    private javax.swing.JLabel botonInicio;
    private javax.swing.JLabel botonListarJuegos;
    private javax.swing.JLabel botonListarUsuarios;
    private javax.swing.JLabel botonReactivar;
    private javax.swing.JLabel botonSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondoReactivar;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanelFondoAjustes;
    private javax.swing.JPanel jPanelFondoCrearAdmin;
    private javax.swing.JPanel jPanelFondoCrearJuego;
    private javax.swing.JPanel jPanelFondoEliminarUsuarios;
    private javax.swing.JPanel jPanelFondoInicio;
    private javax.swing.JPanel jPanelFondoListarJuegos;
    private javax.swing.JPanel jPanelFondoListarUsuarios;
    private javax.swing.JPanel jPanelFondoSalir;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel textoBienvenida;
    private javax.swing.JLabel textoFecha;
    // End of variables declaration//GEN-END:variables
}
