/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUISS;

import Model.Clases.Steam;
import Model.Clases.UserBasico;
import Model.Clases.Validar;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author paola
 */
public class MenuRegistroUser extends javax.swing.JFrame {
     
    private LogIn lw;
    private Steam steam;
    private File file;
    private ObjectMapper mapper;
    public MenuRegistroUser() {
        initComponents();
    }
    
    public MenuRegistroUser(LogIn lw,Steam steam,File file,ObjectMapper mapper) {
        this.lw=lw;
        this.steam=steam;
        this.file=file;
        this.mapper=mapper;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLateral = new javax.swing.JPanel();
        textoNombre = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        textoRegistroUsuario = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoDni = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoContrasenia = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        textoApellido = new javax.swing.JLabel();
        textoDni = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoContrasenia = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        textoNickName = new javax.swing.JLabel();
        imagenSteam = new javax.swing.JLabel();
        fondoBotonRegistrarse = new javax.swing.JPanel();
        botonRegsitrarse = new javax.swing.JLabel();
        campoNickName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1120, 710));
        setResizable(false);

        barraLateral.setBackground(new java.awt.Color(51, 51, 51));
        barraLateral.setPreferredSize(new java.awt.Dimension(1010, 555));

        textoNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("                  Nombre:");

        barraSuperior.setBackground(new java.awt.Color(153, 0, 255));

        textoRegistroUsuario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        textoRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoRegistroUsuario.setText("Registro de nuevo usuario");

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(textoRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoRegistroUsuario)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        campoNombre.setBackground(new java.awt.Color(51, 51, 51));
        campoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setBorder(null);

        campoApellido.setBackground(new java.awt.Color(51, 51, 51));
        campoApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoApellido.setForeground(new java.awt.Color(255, 255, 255));
        campoApellido.setBorder(null);

        campoDni.setBackground(new java.awt.Color(51, 51, 51));
        campoDni.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoDni.setForeground(new java.awt.Color(255, 255, 255));
        campoDni.setBorder(null);

        campoEmail.setBackground(new java.awt.Color(51, 51, 51));
        campoEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(255, 255, 255));
        campoEmail.setBorder(null);

        campoContrasenia.setBackground(new java.awt.Color(51, 51, 51));
        campoContrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        campoContrasenia.setBorder(null);

        textoApellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(255, 255, 255));
        textoApellido.setText("                  Apellido:");

        textoDni.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoDni.setForeground(new java.awt.Color(255, 255, 255));
        textoDni.setText("                          Dni:");

        textoEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoEmail.setForeground(new java.awt.Color(255, 255, 255));
        textoEmail.setText("                     E-Mail:");

        textoContrasenia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        textoContrasenia.setText("            Contraseña:");

        textoNickName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoNickName.setForeground(new java.awt.Color(255, 255, 255));
        textoNickName.setText("      NickName:");

        imagenSteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Captura de pantalla 2023-05-22 194112.jpg"))); // NOI18N
        imagenSteam.setText("jLabel8");

        fondoBotonRegistrarse.setBackground(new java.awt.Color(153, 0, 255));

        botonRegsitrarse.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonRegsitrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonRegsitrarse.setText("    Registrarse");
        botonRegsitrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegsitrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegsitrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegsitrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondoBotonRegistrarseLayout = new javax.swing.GroupLayout(fondoBotonRegistrarse);
        fondoBotonRegistrarse.setLayout(fondoBotonRegistrarseLayout);
        fondoBotonRegistrarseLayout.setHorizontalGroup(
            fondoBotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegsitrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        fondoBotonRegistrarseLayout.setVerticalGroup(
            fondoBotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegsitrarse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        campoNickName.setBackground(new java.awt.Color(51, 51, 51));
        campoNickName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoNickName.setForeground(new java.awt.Color(255, 255, 255));
        campoNickName.setBorder(null);

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoApellido)
                        .addGap(12, 12, 12)
                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoEmail)
                        .addGap(13, 13, 13)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoContrasenia)
                        .addGap(12, 12, 12)
                        .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fondoBotonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(barraLateralLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(textoNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoNickName))
                        .addGroup(barraLateralLayout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(imagenSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraLateralLayout.createSequentialGroup()
                        .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoApellido)
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDni)
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEmail)
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoContrasenia)
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textoNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(barraLateralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(fondoBotonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagenSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegsitrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarseMouseClicked
        // TODO add your handling code here:
        Boolean dniOK=false;
        Boolean mailOK=false;
        Boolean contraOK=false;
        Boolean nickNameOK=false;
        
        UserBasico nuevo= new UserBasico();
        nuevo.setNombre(campoNombre.getText());
        nuevo.setApellido(campoApellido.getText());
        if(Validar.dni(campoDni.getText(), this.steam.getUsersBasicos(),this.steam.getUsuariosPremium())){
            dniOK=true;
            nuevo.setDni(campoDni.getText());
        }else{
            JOptionPane.showMessageDialog(this, "User ya registrado");
        }
        
        ArrayList<Boolean> valiEmail=Validar.mail(campoEmail.getText(), this.steam.getUsuariosPremium(),this.steam.getUsersBasicos());
        if(valiEmail.get(0)==true){
            nuevo.setMail(campoEmail.getText());
            mailOK=true;
        }else if(valiEmail.get(1)==false){
            JOptionPane.showMessageDialog(this, "El mail no continene @ o .com");
        }else if(valiEmail.get(2)==false){
            JOptionPane.showMessageDialog(this, "El mail ya se encuentra registrado en el sistema");
        }
        
        ArrayList<Boolean> validacionContra = Validar.contrasena(campoContrasenia.getText());
            if(validacionContra.get(0)==true){
                nuevo.setContrasena(campoContrasenia.getText());
                contraOK=true;
            }else if(validacionContra.get(1)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos una mayuscula");
            }else if(validacionContra.get(2)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos un numero");
            }else if(validacionContra.get(3)==false){
                JOptionPane.showMessageDialog(this, "Debe contener almenos ocho caracteres");
            }


        if(Validar.nickname(campoNickName.getText(), this.steam.getUsersBasicos(),this.steam.getUsuariosPremium())){
            nuevo.setNickName(campoNickName.getText());
            nickNameOK=true;
        }
        
        if(dniOK && mailOK && contraOK && nickNameOK){
            this.steam.agregarUsuario(nuevo);
            try {
                this.mapper.writerWithDefaultPrettyPrinter().writeValue(this.file,this.steam);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            lw.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Ingreso algun dato incorrecto");
        }
        
    }//GEN-LAST:event_botonRegsitrarseMouseClicked

    private void botonRegsitrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarseMouseEntered
        // TODO add your handling code here:
        fondoBotonRegistrarse.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonRegsitrarseMouseEntered

    private void botonRegsitrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegsitrarseMouseExited
        // TODO add your handling code here:
        fondoBotonRegistrarse.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonRegsitrarseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel botonRegsitrarse;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JPasswordField campoContrasenia;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNickName;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel fondoBotonRegistrarse;
    private javax.swing.JLabel imagenSteam;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel textoApellido;
    private javax.swing.JLabel textoContrasenia;
    private javax.swing.JLabel textoDni;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoNickName;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
