/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUISS;

import Model.Clases.Steam;
import Model.Clases.UserBasico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JPanel;

import com.fasterxml.jackson.databind.ObjectMapper;
import vistas.vistaAjustes;
import vistas.vistaCargarSaldo;
import vistas.vistaComprar;
import vistas.vistaJugar;
import vistas.vistaDeInicio;
import vistas.vistaJugar;
import vistas.vistaListarJuegos;
import vistas.vistaMensajes;

/**
 *
 * @author paola
 */
public class MenuPrincipalUserBasico extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalUserBasico
     */
    
    private LogIn lw;
    private Steam steam;
    private UserBasico usuario;
    private File file;
    private ObjectMapper mapper;
    
    public MenuPrincipalUserBasico(LogIn lw,Steam steam,UserBasico usuario,File file,ObjectMapper mapper) {
        this.lw=lw;
        this.steam=steam;
        this.usuario=usuario;
        this.file=file;
        this.mapper=mapper;
        initComponents();
        initContenido();
        setBienvenida();
        setDate();
        setSaldo();
    }

    private MenuPrincipalUserBasico() {
        
    }
    
    private void setDate(){
    LocalDate now= LocalDate.now();
    int year=now.getYear();
    int dia=now.getDayOfMonth();
    int month=now.getMonthValue();
    String[] meses={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
    textoFecha.setText("Hoy es "+dia+" de "+meses[month-1]+" de " +year);   
    }
    
    private void setSaldo(){
        textoSaldo.setText("Saldo: $"+usuario.getSaldo());
    }
    
    private void setBienvenida(){
        textoBienvenida.setText("Bienvenido "+usuario.getNickName()+" !");
    }
    
    private void initContenido(){
        ShowJPanel(new vistaDeInicio(this.steam,this.usuario));
    }
    
    private void ShowJPanel(JPanel p){
        p.setSize(882,404);
        p.setLocation(0,0);
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jPanelFondoInicio = new javax.swing.JPanel();
        botonInicio = new javax.swing.JLabel();
        jPanelFondoComprar = new javax.swing.JPanel();
        botonComprar = new javax.swing.JLabel();
        jPanelFondoJugar = new javax.swing.JPanel();
        botonJugar = new javax.swing.JLabel();
        jPanelFondoMisJuegos = new javax.swing.JPanel();
        botonMisJuegos = new javax.swing.JLabel();
        jPanelFondoCargarSaldo = new javax.swing.JPanel();
        botonCargarSaldo = new javax.swing.JLabel();
        jPanelFondoMensajes = new javax.swing.JPanel();
        botonMensajes = new javax.swing.JLabel();
        jPanelFondoAjustes = new javax.swing.JPanel();
        botonAjustes = new javax.swing.JLabel();
        jPanelFondoSalir = new javax.swing.JPanel();
        botonSalir = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        textoBienvenida = new javax.swing.JLabel();
        textoFecha = new javax.swing.JLabel();
        textoSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(51, 51, 51));

        menu.setBackground(new java.awt.Color(153, 0, 255));

        jPanelFondoInicio.setBackground(new java.awt.Color(153, 0, 255));

        botonInicio.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("             Inicio");
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoInicioLayout = new javax.swing.GroupLayout(jPanelFondoInicio);
        jPanelFondoInicio.setLayout(jPanelFondoInicioLayout);
        jPanelFondoInicioLayout.setHorizontalGroup(
            jPanelFondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoInicioLayout.setVerticalGroup(
            jPanelFondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoComprar.setBackground(new java.awt.Color(153, 0, 255));

        botonComprar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonComprar.setForeground(new java.awt.Color(255, 255, 255));
        botonComprar.setText("          Comprar");
        botonComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonComprarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoComprarLayout = new javax.swing.GroupLayout(jPanelFondoComprar);
        jPanelFondoComprar.setLayout(jPanelFondoComprarLayout);
        jPanelFondoComprarLayout.setHorizontalGroup(
            jPanelFondoComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoComprarLayout.setVerticalGroup(
            jPanelFondoComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoJugar.setBackground(new java.awt.Color(153, 0, 255));

        botonJugar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonJugar.setForeground(new java.awt.Color(255, 255, 255));
        botonJugar.setText("             Jugar");
        botonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonJugarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoJugarLayout = new javax.swing.GroupLayout(jPanelFondoJugar);
        jPanelFondoJugar.setLayout(jPanelFondoJugarLayout);
        jPanelFondoJugarLayout.setHorizontalGroup(
            jPanelFondoJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoJugarLayout.setVerticalGroup(
            jPanelFondoJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoMisJuegos.setBackground(new java.awt.Color(153, 0, 255));

        botonMisJuegos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonMisJuegos.setForeground(new java.awt.Color(255, 255, 255));
        botonMisJuegos.setText("       Mis Juegos");
        botonMisJuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMisJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMisJuegosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMisJuegosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMisJuegosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoMisJuegosLayout = new javax.swing.GroupLayout(jPanelFondoMisJuegos);
        jPanelFondoMisJuegos.setLayout(jPanelFondoMisJuegosLayout);
        jPanelFondoMisJuegosLayout.setHorizontalGroup(
            jPanelFondoMisJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMisJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoMisJuegosLayout.setVerticalGroup(
            jPanelFondoMisJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMisJuegos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoCargarSaldo.setBackground(new java.awt.Color(153, 0, 255));

        botonCargarSaldo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonCargarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarSaldo.setText("      Cargar Saldo");
        botonCargarSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCargarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarSaldoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoCargarSaldoLayout = new javax.swing.GroupLayout(jPanelFondoCargarSaldo);
        jPanelFondoCargarSaldo.setLayout(jPanelFondoCargarSaldoLayout);
        jPanelFondoCargarSaldoLayout.setHorizontalGroup(
            jPanelFondoCargarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCargarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );
        jPanelFondoCargarSaldoLayout.setVerticalGroup(
            jPanelFondoCargarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCargarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoMensajes.setBackground(new java.awt.Color(153, 0, 255));

        botonMensajes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonMensajes.setForeground(new java.awt.Color(255, 255, 255));
        botonMensajes.setText("         Mensajes");
        botonMensajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMensajesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMensajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMensajesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoMensajesLayout = new javax.swing.GroupLayout(jPanelFondoMensajes);
        jPanelFondoMensajes.setLayout(jPanelFondoMensajesLayout);
        jPanelFondoMensajesLayout.setHorizontalGroup(
            jPanelFondoMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoMensajesLayout.setVerticalGroup(
            jPanelFondoMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMensajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoAjustes.setBackground(new java.awt.Color(153, 0, 255));

        botonAjustes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonAjustes.setForeground(new java.awt.Color(255, 255, 255));
        botonAjustes.setText("           Ajustes");
        botonAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAjustesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAjustesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoAjustesLayout = new javax.swing.GroupLayout(jPanelFondoAjustes);
        jPanelFondoAjustes.setLayout(jPanelFondoAjustesLayout);
        jPanelFondoAjustesLayout.setHorizontalGroup(
            jPanelFondoAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoAjustesLayout.setVerticalGroup(
            jPanelFondoAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAjustes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelFondoSalir.setBackground(new java.awt.Color(153, 0, 255));

        botonSalir.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("              Salir");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoSalirLayout = new javax.swing.GroupLayout(jPanelFondoSalir);
        jPanelFondoSalir.setLayout(jPanelFondoSalirLayout);
        jPanelFondoSalirLayout.setHorizontalGroup(
            jPanelFondoSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoSalirLayout.setVerticalGroup(
            jPanelFondoSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoMisJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoCargarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelFondoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoMisJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoCargarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/store_home_share.jpg"))); // NOI18N
        header.setText("jLabel12");

        contenido.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textoBienvenida.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        textoBienvenida.setText("Bienvenido {nickname} !");

        textoFecha.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoFecha.setForeground(new java.awt.Color(255, 255, 255));
        textoFecha.setText("Hoy es {dia} de {mes} del {anio}");

        textoSaldo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textoSaldo.setForeground(new java.awt.Color(255, 255, 255));
        textoSaldo.setText("Saldo : ${saldo}");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 249, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaDeInicio(this.steam,this.usuario));
        setSaldo();
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered
        // TODO add your handling code here:
        jPanelFondoInicio.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited
        // TODO add your handling code here:
        jPanelFondoInicio.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonInicioMouseExited

    private void botonComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaComprar(this.steam,this.usuario));
        setSaldo();
    }//GEN-LAST:event_botonComprarMouseClicked

    private void botonComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseEntered
        // TODO add your handling code here:
        jPanelFondoComprar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonComprarMouseEntered

    private void botonComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseExited
        // TODO add your handling code here:
        jPanelFondoComprar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonComprarMouseExited

    private void botonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaJugar(this.usuario));
        setSaldo();
    }//GEN-LAST:event_botonJugarMouseClicked

    private void botonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseEntered
        // TODO add your handling code here:
        jPanelFondoJugar.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonJugarMouseEntered

    private void botonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseExited
        // TODO add your handling code here:
        jPanelFondoJugar.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonJugarMouseExited

    private void botonMisJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisJuegosMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaListarJuegos(this.usuario.getComprados()));
        setSaldo();
    }//GEN-LAST:event_botonMisJuegosMouseClicked

    private void botonMisJuegosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisJuegosMouseEntered
        // TODO add your handling code here:
        jPanelFondoMisJuegos.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonMisJuegosMouseEntered

    private void botonMisJuegosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisJuegosMouseExited
        // TODO add your handling code here:
        jPanelFondoMisJuegos.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonMisJuegosMouseExited

    private void botonCargarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaCargarSaldo(this.usuario));
        setSaldo();
    }//GEN-LAST:event_botonCargarSaldoMouseClicked

    private void botonCargarSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseEntered
        // TODO add your handling code here:
        jPanelFondoCargarSaldo.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonCargarSaldoMouseEntered

    private void botonCargarSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarSaldoMouseExited
        // TODO add your handling code here:
        jPanelFondoCargarSaldo.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonCargarSaldoMouseExited

    private void botonMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMensajesMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new vistaMensajes(this.steam,this.usuario));
        setSaldo();
    }//GEN-LAST:event_botonMensajesMouseClicked

    private void botonMensajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMensajesMouseEntered
        // TODO add your handling code here:
        jPanelFondoMensajes.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonMensajesMouseEntered

    private void botonMensajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMensajesMouseExited
        // TODO add your handling code here:
        jPanelFondoMensajes.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonMensajesMouseExited

    private void botonAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseClicked
        // TODO add your handling code here:
        vistaAjustes ajustes=new vistaAjustes(this.usuario,this.steam,this.lw,null,this,this.mapper,this.file);
        ShowJPanel(ajustes);
        setSaldo();
    }//GEN-LAST:event_botonAjustesMouseClicked

    private void botonAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseEntered
        // TODO add your handling code here:
        jPanelFondoAjustes.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonAjustesMouseEntered

    private void botonAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseExited
        // TODO add your handling code here:
        jPanelFondoAjustes.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonAjustesMouseExited

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        // TODO add your handling code here:
        this.steam.agregarUsuario(usuario);
        try {
            this.mapper.writerWithDefaultPrettyPrinter().writeValue(this.file,this.steam);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        lw.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
        jPanelFondoSalir.setBackground(new Color(153,0,236));
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
        jPanelFondoSalir.setBackground(new Color(153,0,255));
    }//GEN-LAST:event_botonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUserBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUserBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUserBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUserBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalUserBasico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonAjustes;
    private javax.swing.JLabel botonCargarSaldo;
    private javax.swing.JLabel botonComprar;
    private javax.swing.JLabel botonInicio;
    private javax.swing.JLabel botonJugar;
    private javax.swing.JLabel botonMensajes;
    private javax.swing.JLabel botonMisJuegos;
    private javax.swing.JLabel botonSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanelFondoAjustes;
    private javax.swing.JPanel jPanelFondoCargarSaldo;
    private javax.swing.JPanel jPanelFondoComprar;
    private javax.swing.JPanel jPanelFondoInicio;
    private javax.swing.JPanel jPanelFondoJugar;
    private javax.swing.JPanel jPanelFondoMensajes;
    private javax.swing.JPanel jPanelFondoMisJuegos;
    private javax.swing.JPanel jPanelFondoSalir;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel textoBienvenida;
    private javax.swing.JLabel textoFecha;
    private javax.swing.JLabel textoSaldo;
    // End of variables declaration//GEN-END:variables
}
